name: "boxing"
data_dir: "./data/boxing"


# Boxing-specific logic
joints: 25                 # Body25 joints 25*3 = 75
random_face: true

# Prediction window (1s input -> 1s output @ 60fps)
input_n: 30
output_n: 30

# Sampling settings
skip_rate: 10
val_skip_rate: 10
neutral_ratio: 0.25

