name: "h36m"
data_dir: "./data/h36m"

# H3.6M alignment and split settings
protocol: "standard"          
joints: 17

# 預測視窗
input_n: 25
output_n: 100

# 採樣與丟失設定
skip_rate: 5
val_skip_rate: 5           
downsample: 2
miss_type: "no_miss"
miss_rate: 0

# 其他資料處理
no_overlap: false
all_data: true
data_ratio: 1.0
pad_short_sequences: false
