defaults:
  - dataset: finefs
  - model: sft_baseline
  - _self_

# Quick-test switch (if true, only 1% of every dataset is used)
quick_test: false

# Training loop hyperparameters
training:
  epochs: 500
  batch_size: 32
  batch_size_test: 32
  lr: 1.0e-3
  valid_epoch_interval: 10
  grad_clip: 1.0
  cfg_dropout_prob: 0.05    # Probability of zeroing out the text embedding during SFT, used to improve CFG robustness
  gen_type: "ddpm"          # Underlying generative model architecture: 'ddpm' (Diffusion) or 'flow_matching'
  save_top_k: -1            # Limit on the number of checkpoints to save (-1 means save all, for tracking training dynamics)

# PyTorch Lightning system settings
system:
  accelerator: "gpu"
  devices: [1,2]            # Use all available GPUs
  strategy: "ddp"
  precision: "32-true"   # Supports 16-mixed to save GPU memory
  seed: 42

# Define an experiment name tag, easily overridable (e.g. python train.py exp_name=sft+moe)
exp_name: "sft"

# Override Hydra's default output directory naming scheme
hydra:
  run:
    dir: outputs/${exp_name}_${dataset.name}_${now:%Y-%m-%d_%H-%M}
